const candidates = [
  {
    name: "Abigail Binay",
    party: "NPC",
    alliance: "Alyansa para sa Bagong Pilipinas",
    image: "/abigail-binay.jpg",
    position: "Senator",
    age: 49,
    hometown: "Makati City",
    education: "Bachelor's Degree in Business Administration",
    experience: "Mayor of Makati",
    previousPosition: "Mayor",
    achievements: "Improved healthcare system in Makati"
  },
  {
    name: "Allen Capuyan",
    party: "PPP",
    alliance: "—",
    image: "/allen-capuyan.webp",
    position: "Senator",
    age: 45,
    hometown: "Sultan Kudarat",
    education: "Bachelor's Degree in Political Science",
    experience: "Public servant and policy adviser",
    previousPosition: "—",
    achievements: "Contributed to the peace process"
  },
  {
    name: "Amirah Lidasan",
    party: "Makabayan",
    alliance: "Oposisyon ng Bayan",
    image: "/amirah-lidasan.webp",
    position: "Representative",
    age: 40,
    hometown: "Mindanao",
    education: "Master's Degree in Political Science",
    experience: "Human rights advocate",
    previousPosition: "—",
    achievements: "Fought for the rights of indigenous people"
  },
  {
    name: "Angelo de Alban",
    party: "Independent",
    alliance: "—",
    image: "/angelo-de-alban.webp",
    position: "Senator",
    age: 38,
    hometown: "Baguio",
    education: "Law Degree",
    experience: "Civil rights lawyer",
    previousPosition: "—",
    achievements: "Advocated for human rights"
  },
  {
    name: "Arlene Brosas",
    party: "Makabayan",
    alliance: "Oposisyon ng Bayan",
    image: "/arlene-brosas.jpg",
    position: "Representative",
    age: 45,
    hometown: "Davao City",
    education: "Bachelor's Degree in Sociology",
    experience: "Advocate for women's rights",
    previousPosition: "—",
    achievements: "Led various women's rights campaigns"
  },
  {
    name: "Arnel Escobal",
    party: "PM",
    alliance: "—",
    image: "/arnel-escobal.jpg",
    position: "Senator",
    age: 52,
    hometown: "Cebu",
    education: "Bachelor's Degree in Economics",
    experience: "Policy maker and economic adviser",
    previousPosition: "—",
    achievements: "Contributed to economic reforms"
  },
  {
    name: "Bam Aquino",
    party: "KANP",
    alliance: "KiBam",
    image: "/bam-aquino.jpg",
    position: "Senator",
    age: 47,
    hometown: "Quezon City",
    education: "Bachelor's Degree in Management Engineering",
    experience: "Senator and public servant",
    previousPosition: "Senator",
    achievements: "Improved public education system"
  },
  {
    name: "Ben Tulfo",
    party: "Independent",
    alliance: "—",
    image: "/ben-tulfo.webp",
    position: "Senator",
    age: 59,
    hometown: "Quezon City",
    education: "Bachelor's Degree in Journalism",
    experience: "Television host and journalist",
    previousPosition: "—",
    achievements: "Advocated for press freedom"
  },
  {
    name: "Bong Go",
    party: "PDP",
    alliance: "Partido Demokratiko Pilipino",
    image: "/bong-go.webp",
    position: "Senator",
    age: 49,
    hometown: "Davao City",
    education: "Bachelor's Degree in Political Science",
    experience: "Former special assistant to the President",
    previousPosition: "Special Assistant to the President",
    achievements: "Contributed to government infrastructure projects"
  },
  {
    name: "Bong Revilla",
    party: "Lakas",
    alliance: "Alyansa para sa Bagong Pilipinas",
    image: "/bong-revilla.JPG",
    position: "Senator",
    age: 58,
    hometown: "Cavite",
    education: "Bachelor's Degree in Arts",
    experience: "Actor and public servant",
    previousPosition: "Senator",
    achievements: "Supported health and education programs"
  },
  {
    name: "Bonifacio Bosita",
    party: "Independent",
    alliance: "Riding-in-tandem Team",
    image: "/bonifacio-bosita.jpg",
    position: "Representative",
    age: 45,
    hometown: "Taguig City",
    education: "Bachelor's Degree in Law",
    experience: "Lawyer and businessman",
    previousPosition: "—",
    achievements: "Advocated for legal reforms"
  },
  {
    name: "Camille Villar",
    party: "Nacionalista",
    alliance: "Alyansa para sa Bagong Pilipinas",
    image: "/camille-villar.jpg",
    position: "Senator",
    age: 43,
    hometown: "Las Piñas",
    education: "Bachelor's Degree in Business Administration",
    experience: "Former House Representative",
    previousPosition: "Representative",
    achievements: "Led initiatives on housing and livelihood programs"
  }
];

export default candidates;
